# Generated by Django 4.1.3 on 2022-12-06 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_added_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="added_by",
        ),
    ]
